- name: Task2-vm1
  hosts: privatenet-us-vm1
  tasks:
    - name: Copy rpm file to server
      get_url:
        url: https://cloud.imhio.com/s/aDH5ktf99CG7k8D/download
        dest: /tmp/tcg.rpm
        mode: '0440'

    - name: Install package.
      yum:
        name: /tmp/tcg.rpm
        state: present

    - name: Copy config
      copy:
        src: /etc/tcg/tcg.config.sample.json
        dest: /etc/tcg/tcg.json
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: tcg mysql conf 1st
      replace:
        path: /etc/tcg/tcg.json
        regexp: '"host": "127.0.0.1",'
        replace: '"host": "{{ dbip }}",'

    - name: tcg mysql conf 2st
      lineinfile:
        path: /etc/tcg/tcg.json
        regexp: '"host": "{{ dbip }}",'
        line: '"host": "127.0.0.1",'

    - name: tcg mysql conf 3rd
      lineinfile:
        path: /etc/tcg/tcg.json
        regexp: '"host": "{{ dbip }}",'
        line: '"host": "127.0.0.1",'
        firstmatch: yes

    - name: tcg mysql conf 4th
      lineinfile:
        path: /etc/tcg/tcg.json
        insertafter: 'mysql'
        firstmatch: yes
        regexp: 'pass'
        line: '"pass": "{{ dbusrpwd }}",'

- name: Task2-vm2
  hosts: privatenet-us-vm2
  tasks:
    - parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present

    - filesystem:
        fstype: ext2
        dev: /dev/sdb1

    - mount:
        fstype: ext2
        src: /dev/sdb1
        path: /dbfiles
        state: mounted

    - name: Install mariadb plus semanage
      action: yum name={{ item }}
      with_items:
        - mariadb-server
        - mariadb-libs
        - mariadb
        - policycoreutils-python
        - MySQL-python

    - name: Start the mariadb service
      action: service name=mariadb state=started

    - name: mariadb | Stop service to move data
      service:
        name: mariadb
        state: stopped
        enabled: yes

    - name: mariadb | Copy data plus permissions
      shell: "{{ item }}"
      with_items:
        - "cp -R -p /var/lib/mysql /dbfiles "
        - "semanage fcontext -a -t mysqld_db_t \"/dbfiles/mysql(/.*)?\" "
        - "restorecon -Rv /dbfiles/mysql "
        - "firewall-cmd --permanent --add-source=172.16.0.0/24"
        - "firewall-cmd --reload"

    - name: mariadb | Update mariadb configuration
      replace:
        dest: /etc/my.cnf
        regexp: '/var/lib/mysql'
        replace: '/dbfiles/mysql'

    - name: mariadb | client settings /etc/my.cnf
      blockinfile:
        path: /etc/my.cnf
        insertafter: '^pid-file=/var/run/mariadb/mariadb.pid'
        block: |
          [client]
          socket=/dbfiles/mysql/mysql.sock


    - name: mariadb | Start service after moving data
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: mariadb | Check if old data directory is removed
      file:
        path: /var/lib/mysql
        state: absent
          
    - name: mariadb | root password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        login_unix_socket: '/dbfiles/mysql/mysql.sock'
        name: 'root'
        password: '{{ dbrootpwd }}'
        host_all: yes
        state: present

    - name: mariadb | a new database tcg_db
      mysql_db:
        login_user: 'root'
        login_password: '{{ dbrootpwd }}'
        login_unix_socket: '/dbfiles/mysql/mysql.sock'
        name: tcg_db
        state: present

    - name: mariadb | user tcg
      mysql_user:
        login_user: 'root'
        login_password: '{{ dbrootpwd }}' 
        login_unix_socket: '/dbfiles/mysql/mysql.sock'
        name: tcg_user 
        priv: tcg_db.*:ALL
        password: "{{ dbusrpwd }}"
        state: present

- name: Task2-vm1-start-service
  hosts: privatenet-us-vm1
  tasks:
    - name: Enable service tcg
      systemd:
        name: tcg
        enabled: yes
        masked: no

    - name: Restart service tcg
      systemd:
        state: restarted
        daemon_reload: yes
        name: tcg