- name: Task2-vm1
  hosts: privatenet-us-vm1
  tasks:
    - name: Copy rpm file to server.
      get_url:
        url: https://cloud.imhio.com/s/aDH5ktf99CG7k8D/download
        dest: /tmp/tcg.rpm
        mode: '0440'

    - name: Install package.
      yum:
        name: /tmp/tcg.rpm
        state: present

    - name: Copy config.
      copy:
        src: /etc/tcg/tcg.config.sample.json
        dest: /etc/tcg/tcg.json
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

- name: Task2-vm2
  hosts: privatenet-us-vm2
  tasks:
    - parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present

    - filesystem:
        fstype: ext2
        dev: /dev/sdb1

    - mount:
        fstype: ext2
        src: /dev/sdb1
        path: /dbfiles
        state: mounted

    - name: Install mariadb plus semanage
      action: yum name={{ item }}
      with_items:
        - mariadb-server
        - mariadb-libs
        - mariadb
        - policycoreutils-python

    - name: Start the mariadb service
      action: service name=mariadb state=started

    - name: mariadb | Stop service to move data
      service:
        name: mariadb
        state: stopped
        enabled: yes

    - name: mariadb | Copy data plus permissions
      shell: "{{ item }}"
      with_items:
        - "cp -R -p /var/lib/mysql /dbfiles "
        - "semanage fcontext -a -t mysqld_db_t \"/dbfiles/mysql(/.*)?\" "
        - "restorecon -Rv /dbfiles/mysql "

    - name: mariadb | Update mariadb configuration
      replace:
        dest: /etc/my.cnf
        regexp: '/var/lib/mysql'
        replace: '/dbfiles/mysql'

    - name: mariadb | Start service after moving data
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: mariadb | Check if old data directory is removed
      file:
        path: /var/lib/mysql
        state: absent

    - name: Create a new database tcg_db
      mysql_db:
        name: tcg_db
        login_host: 172.16.0.3
        state: present

    - name: Update mysql root password
      mysql_user: name=root host={{item}} password="mysql-root-password"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql tcg password
      mysql_user: name=tcg host={{item}} password="mysql-tcg-password"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
        - 172.16.0.3
